### ISSUE TITLE
Issue on Samsung Galaxy S9 Plus Exynos (SM-G965F)

### ISSUE THREAD

**Issue by mssadewa** [EnesSastim/Downloads#49]
My Environments is : 
- Samsung Galaxy S9+ Exynos (SM-G965F)
- Stock Latest Firmware CSH5 with Oreo vendor BRJ6.
- Endurance AOSP kernel 2.0.27
- Official TWRP 3.3.1-0

Issue I've found : 
- Wifi can't enable.
- No navigation.
- Sim card not detected.
- Freeze opening camera.

_Smoothly UI and clean looks! I love it._ 

Below is the dmesg and recovery logs.
[logs_201909291714.zip](https://github.com/EnesSastim/Downloads/files/3667401/logs_201909291714.zip)

**Comment by mssadewa** [comment]
Tring to filter out about wifi, it seems the wifi didn't get the power. is that right?

> --------- beginning of system
09-29 18:44:00.430  4464  4464 I wificond: wificond is starting up...
09-29 18:44:02.369  4650  4650 I SystemServiceManager: Starting com.android.server.wifi.WifiService
09-29 18:44:02.426  4650  4650 I SystemServiceManager: Starting com.android.server.wifi.scanner.WifiScanningService
09-29 18:44:02.427  4650  4650 I SystemServiceManager: Starting com.android.server.wifi.p2p.WifiP2pService
09-29 18:44:02.435  4650  4650 D ConnectivityService: wifiOnly=false
--------- beginning of main
09-29 18:44:24.151  4650  4672 E **BatteryExternalStatsWorker: no controller energy info supplied for wifi**
09-29 18:44:24.235  4389  5255 E WifiHAL : wifi_event_loop: Read after POLL returned 4, error no = 0 (Success)
09-29 18:44:24.235  4389  5255 I WifiHAL : Exit wifi_event_loop
09-29 18:44:24.235  4389  4389 E WifiHAL : wifi_cleanup: Read after POLL returned 4, error no = 0 (Success)
09-29 18:44:25.315  4389  4389 I WifiHAL : Initializing wifi
09-29 18:44:45.401  4650  4672 E **BatteryExternalStatsWorker: no controller energy info supplied for wifi**
09-29 18:44:45.406  4389  6370 E WifiHAL : wifi_event_loop: Read after POLL returned 4, error no = 0 (Success)
09-29 18:44:45.406  4389  6370 I WifiHAL : Exit wifi_event_loop
09-29 18:44:45.406  4389  4389 E WifiHAL : wifi_cleanup: Read after POLL returned 4, error no = 0 (Success)
09-29 18:44:46.481  7144  7144 D PHH     : Couldn't find hostapd service
09-29 18:44:46.481  7144  7144 D PHH     : java.util.NoSuchElementException
09-29 18:44:46.481  7144  7144 D PHH     :      at android.os.HwBinder.getService(Native Method)
09-29 18:44:46.481  7144  7144 D PHH     :      at android.os.HwBinder.getService(HwBinder.java:91)
09-29 18:44:46.481  7144  7144 D PHH     :      at android.hardware.wifi.hostapd.V1_0.IHostapd.getService(IHostapd.java:48)
09-29 18:44:46.481  7144  7144 D PHH     :      at android.hardware.wifi.hostapd.V1_0.IHostapd.getService(IHostapd.java:52)
09-29 18:44:46.481  7144  7144 D PHH     :      at me.phh.treble.app.Hostapd$Companion.startup(Hostapd.kt:118)
09-29 18:44:46.481  7144  7144 D PHH     :      at me.phh.treble.app.EntryService$onCreate$9.invoke(EntryService.kt:39)
09-29 18:44:46.481  7144  7144 D PHH     :      at me.phh.treble.app.EntryService$onCreate$9.invoke(EntryService.kt:12)
09-29 18:44:46.481  7144  7144 D PHH     :      at me.phh.treble.app.EntryService.tryC(EntryService.kt:22)
09-29 18:44:46.481  7144  7144 D PHH     :      at me.phh.treble.app.EntryService.onCreate(EntryService.kt:39)
09-29 18:44:46.481  7144  7144 D PHH     :      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3570)
09-29 18:44:46.481  7144  7144 D PHH     :      at android.app.ActivityThread.access$1300(ActivityThread.java:200)
09-29 18:44:46.481  7144  7144 D PHH     :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
09-29 18:44:46.481  7144  7144 D PHH     :      at android.os.Handler.dispatchMessage(Handler.java:106)
09-29 18:44:46.481  7144  7144 D PHH     :      at android.os.Looper.loop(Looper.java:193)
09-29 18:44:46.481  7144  7144 D PHH     :      at android.app.ActivityThread.main(ActivityThread.java:6718)
09-29 18:44:46.481  7144  7144 D PHH     :      at java.lang.reflect.Method.invoke(Native Method)
09-29 18:44:46.481  7144  7144 D PHH     :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-29 18:44:46.481  7144  7144 D PHH     :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-29 18:44:46.804  4389  4389 I WifiHAL : Initializing wifi
09-29 18:45:06.937  4650  4672 E **BatteryExternalStatsWorker: no controller energy info supplied for wifi**
09-29 18:45:06.959  4650  4672 E **BatteryExternalStatsWorker: no controller energy info supplied for wifi**
09-29 18:45:15.449  6848  6848 I SetupWizard: [AccessPointsMonitor] Pausing wifi scanner.
09-29 18:45:49.720  4389  7194 E WifiHAL : wifi_event_loop: Read after POLL returned 4, error no = 0 (Success)
09-29 18:45:49.720  4389  7194 I WifiHAL : Exit wifi_event_loop
09-29 18:45:49.721  4389  4389 E WifiHAL : wifi_cleanup: Read after POLL returned 4, error no = 0 (Success)
09-29 18:45:51.049  4389  4389 I WifiHAL : Initializing wifi
09-29 18:46:11.155  4650  4672 E **BatteryExternalStatsWorker: no controller energy info supplied for wifi**
09-29 18:46:11.164  4389  7526 E WifiHAL : wifi_event_loop: Read after POLL returned 4, error no = 0 (Success)
09-29 18:46:11.164  4389  7526 I WifiHAL : Exit wifi_event_loop
09-29 18:46:11.164  4389  4389 E WifiHAL : wifi_cleanup: Read after POLL returned 4, error no = 0 (Success)
09-29 18:46:12.646  4389  4389 I WifiHAL : Initializing wifi
09-29 18:46:32.763  4650  4672 E **BatteryExternalStatsWorker: no controller energy info supplied for wifi**
09-29 18:46:32.783  4650  4672 E **BatteryExternalStatsWorker: no controller energy info supplied for wifi**
09-29 18:54:23.654  4389  7537 E WifiHAL : wifi_event_loop: Read after POLL returned 4, error no = 0 (Success)
09-29 18:54:23.654  4389  7537 I WifiHAL : Exit wifi_event_loop
09-29 18:54:23.654  4389  4389 E WifiHAL : wifi_cleanup: Read after POLL returned 4, error no = 0 (Success)
09-29 18:54:25.029  4389  4389 I WifiHAL : Initializing wifi
09-29 18:54:45.150  4650  4672 E **BatteryExternalStatsWorker: no controller energy info supplied for wifi**
09-29 18:54:45.162  4389  7954 E WifiHAL : wifi_event_loop: Read after POLL returned 4, error no = 0 (Success)
09-29 18:54:45.162  4389  4389 E WifiHAL : wifi_cleanup: Read after POLL returned 4, error no = 0 (Success)
09-29 18:54:45.163  4389  7954 I WifiHAL : Exit wifi_event_loop
09-29 18:54:46.529  4389  4389 I WifiHAL : Initializing wifi
09-29 18:54:46.554  4650  4753 D HalDevMgr: Interface available listener dispatched: ifaceType=2, listener=com.android.server.wifi.HalDeviceManager$InterfaceAvailableForRequestListenerProxy@b8c4c00
09-29 18:54:46.555  4650  4753 D HalDevMgr: registerInterfaceAvailableForRequestListener: ifaceType=2, listener=com.android.server.wifi.p2p.WifiP2pNative$InterfaceAvailableListenerInternal@b8c4c00, handler=Handler (com.android.internal.util.StateMachine$SmHandler) {1e48c39}
09-29 18:54:46.555  4650  4753 D HalDevMgr: registerInterfaceAvailableForRequestListener: dup listener skipped: com.android.server.wifi.p2p.WifiP2pNative$InterfaceAvailableListenerInternal@b8c4c00
09-29 18:55:06.651  4650  4672 E **BatteryExternalStatsWorker: no controller energy info supplied for wifi**
09-29 18:55:06.659  4650  4752 I WifiScanningService: wifi driver unloaded
09-29 18:55:06.670  4650  4672 E **BatteryExternalStatsWorker: no controller energy info supplied for wifi**

**Comment by mssadewa** [comment]
better to buy pixel devices
